<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="10" failures="1">
  <testsuite name="Root Suite" timestamp="2019-03-27T23:01:30" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="dom-testing-library commands" timestamp="2019-03-27T23:01:30" tests="10" failures="1" time="0">
    <testcase name="dom-testing-library commands &quot;before each&quot; hook for &quot;getByPlaceholderText&quot;" time="0" classname="&quot;before each&quot; hook for &quot;getByPlaceholderText&quot;">
      <failure message="cy.visit() failed trying to load:

http://localhost:13370/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:13370

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ECONNREFUSED 127.0.0.1:13370
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)


Because this error occurred during a &apos;before each&apos; hook we are skipping the remaining tests in the current suite: &apos;dom-testing-library commands&apos;" type="CypressError"><![CDATA[CypressError: cy.visit() failed trying to load:

http://localhost:13370/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:13370

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

Error: connect ECONNREFUSED 127.0.0.1:13370
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)


Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'dom-testing-library commands'
    at Object.cypressErr (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:65727:11)
    at Object.throwErr (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:65692:18)
    at Object.throwErrByPath (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:65719:17)
    at https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:56269:31
    at visitFailedByErr (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:55840:12)
    at https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:56268:22
    at tryCatcher (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:131273:23)
    at Promise._settlePromiseFromHandler (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:129291:31)
    at Promise._settlePromise (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:129348:18)
    at Promise._settlePromise0 (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:129393:10)
    at Promise._settlePromises (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:129468:18)
    at Async._drainQueue (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:126197:16)
    at Async._drainQueues (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:126207:10)
    at Async.drainQueues (https://the-internet.herokuapp.com/__cypress/runner/cypress_runner.js:126081:14)
    at <anonymous>]]></failure>
    </testcase>
  </testsuite>
</testsuites>